// <auto-generated />
using System;
using Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SEDAPITESTINGMODULE.DatabaseManager.Migrations
{
    [DbContext(typeof(SED))]
    [Migration("20230227164236_2023_02_27")]
    partial class _2023_02_27
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.Context.SEDDb._Carousel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Image")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ID")
                        .HasName("PK_dbo._Carousel_ID");

                    b.ToTable("_Carousel", (string)null);
                });

            modelBuilder.Entity("Database.Context.SEDDb._Categories", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Image")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID")
                        .HasName("PK_dbo._Categories_ID");

                    b.ToTable("_Categories", (string)null);
                });

            modelBuilder.Entity("Database.Context.SEDDb._Items", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Category_Id")
                        .HasColumnType("int");

                    b.Property<string>("Descr")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Image")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Section_Id")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("PK_dbo._Items_ID");

                    b.HasIndex("Category_Id");

                    b.HasIndex("Section_Id");

                    b.ToTable("_Items", (string)null);
                });

            modelBuilder.Entity("Database.Context.SEDDb._Sections", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID")
                        .HasName("PK_dbo._Sections_ID");

                    b.ToTable("_Sections", (string)null);
                });

            modelBuilder.Entity("Database.Context.SEDDb._Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("PK_dbo._Users_ID");

                    b.ToTable("_Users", (string)null);
                });

            modelBuilder.Entity("Database.Context.SEDDb._Items", b =>
                {
                    b.HasOne("Database.Context.SEDDb._Categories", "Category")
                        .WithMany("Items")
                        .HasForeignKey("Category_Id")
                        .IsRequired()
                        .HasConstraintName("FK_dbo._Categories._Categories_ID");

                    b.HasOne("Database.Context.SEDDb._Sections", "Section")
                        .WithMany("Items")
                        .HasForeignKey("Section_Id")
                        .IsRequired()
                        .HasConstraintName("FK_dbo._Categories._Sections_ID");

                    b.Navigation("Category");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Database.Context.SEDDb._Categories", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Database.Context.SEDDb._Sections", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
