// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFrODS4IOKBRR_5DuvdCphd9VYvA9xZFI',
    appId: '1:602406913114:web:4129250def570b20928463',
    messagingSenderId: '602406913114',
    projectId: 'sed-inc',
    authDomain: 'sed-inc.firebaseapp.com',
    storageBucket: 'sed-inc.appspot.com',
    measurementId: 'G-3NCQMVE3YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE101wWvMSUKfwqnNrOvaChkAXx9tKOU8',
    appId: '1:602406913114:android:d74d89896e0db7a8928463',
    messagingSenderId: '602406913114',
    projectId: 'sed-inc',
    storageBucket: 'sed-inc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj8AwjbqfmWKCdSlxF9wLQS8pV_zVmr_4',
    appId: '1:602406913114:ios:8dc09ad359ffe0c9928463',
    messagingSenderId: '602406913114',
    projectId: 'sed-inc',
    storageBucket: 'sed-inc.appspot.com',
    iosClientId: '602406913114-0i1dtatato7bevl1aku9mlt3e92ont0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.sed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj8AwjbqfmWKCdSlxF9wLQS8pV_zVmr_4',
    appId: '1:602406913114:ios:8dc09ad359ffe0c9928463',
    messagingSenderId: '602406913114',
    projectId: 'sed-inc',
    storageBucket: 'sed-inc.appspot.com',
    iosClientId: '602406913114-0i1dtatato7bevl1aku9mlt3e92ont0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.sed',
  );
}
